"""Quiz question bank — 10 questions per week, auto-graded.

Categories:
  - concept     概念理解
  - application 應用題
  - code        程式碼閱讀
"""

QUIZ_BANK: dict[int, list[dict]] = {
    # ── Week 1  ML/DL 概論與 Python 環境 ─────────────────────────────
    1: [
        {"id": "w01q01", "question": "以下哪個描述最正確？",
         "options": ["AI、ML、DL 是同義詞", "DL 包含 ML 包含 AI", "AI 包含 ML，ML 包含 DL", "ML 和 DL 互不相關"],
         "answer": 2, "explanation": "AI 是最廣的概念，ML 是 AI 的子集，DL 是 ML 的子集，三者是包含關係。", "category": "concept"},
        {"id": "w01q02", "question": "機器學習的核心概念是？",
         "options": ["人工撰寫所有規則", "從資料中自動學習規律", "使用最快的電腦", "模擬人類的外觀"],
         "answer": 1, "explanation": "ML 的核心在於讓電腦從資料中自動發現規律和模式，而非由人類手動撰寫每條規則。", "category": "concept"},
        {"id": "w01q03", "question": "醫院用 AI 判讀 X 光影像來檢測肺炎，這屬於哪種學習？",
         "options": ["非監督式學習", "監督式學習", "強化學習", "規則式系統"],
         "answer": 1, "explanation": "有標記的 X 光影像（正常/肺炎）作為訓練資料，模型學會從影像預測診斷結果，這是典型的監督式學習。", "category": "application"},
        {"id": "w01q04", "question": "非監督式學習的特點是？",
         "options": ["需要大量標記資料", "在無標籤資料中發現結構", "透過獎勵信號學習", "只能用於分類問題"],
         "answer": 1, "explanation": "非監督式學習不需要標籤，而是自動發現資料中的結構或分群，如客戶分群、異常偵測。", "category": "concept"},
        {"id": "w01q05", "question": "ML 專案中，通常花最多時間的階段是？",
         "options": ["選擇模型", "資料收集與處理", "模型訓練", "部署上線"],
         "answer": 1, "explanation": "實務上約 80% 的時間用在資料收集、清理和特徵工程，這是 ML 成功的關鍵。", "category": "application"},
        {"id": "w01q06", "question": "訓練集 (Training Set) 和測試集 (Test Set) 為什麼要分開？",
         "options": ["節省記憶體", "加快訓練速度", "評估模型對未見過資料的表現", "讓模型更複雜"],
         "answer": 2, "explanation": "分開的目的是用測試集模擬「未來的新資料」，評估模型的泛化能力，而非只看訓練表現。", "category": "concept"},
        {"id": "w01q07", "question": "什麼是過擬合 (Overfitting)？",
         "options": ["模型訓練時間太長", "模型在訓練集表現好但在新資料表現差", "模型的參數太少", "模型的學習率太大"],
         "answer": 1, "explanation": "過擬合就像「死記考古題但不會變化題」，模型記住了訓練資料的雜訊而非真正的規律。", "category": "concept"},
        {"id": "w01q08", "question": "Python 中用來處理表格資料的主要套件是？",
         "options": ["NumPy", "Pandas", "Matplotlib", "Scikit-learn"],
         "answer": 1, "explanation": "Pandas 的 DataFrame 結構專門用來處理表格型資料，是資料科學工作中最常用的套件。", "category": "code"},
        {"id": "w01q09", "question": "Jupyter Notebook 的副檔名是？",
         "options": [".py", ".ipynb", ".jnb", ".nb"],
         "answer": 1, "explanation": "ipynb 代表 Interactive Python Notebook，是 Jupyter 的檔案格式。", "category": "code"},
        {"id": "w01q10", "question": "回歸 (Regression) 和分類 (Classification) 的主要差異是？",
         "options": ["回歸速度快，分類速度慢", "回歸預測連續數值，分類預測類別", "回歸用深度學習，分類用機器學習", "兩者完全相同"],
         "answer": 1, "explanation": "回歸預測的是連續值（如房價、溫度），分類預測的是離散類別（如是否為垃圾郵件）。", "category": "concept"},
    ],

    # ── Week 2  EDA 探索式資料分析 ───────────────────────────────────
    2: [
        {"id": "w02q01", "question": "EDA 的全稱是？",
         "options": ["Exploratory Data Analysis", "Extended Data Algorithm",
                     "Efficient Data Architecture", "Evaluated Data Approach"], "answer": 0,
         "explanation": "EDA 是 Exploratory Data Analysis（探索式資料分析），旨在透過視覺化與統計方法理解資料。",
         "category": "concept"},
        {"id": "w02q02", "question": "觀察兩個連續變數關係時最適合用什麼圖？",
         "options": ["長條圖", "散佈圖", "圓餅圖", "直方圖"], "answer": 1,
         "explanation": "散佈圖（scatter plot）以 x、y 座標呈現兩個連續變數的關係，最能觀察其相關性。",
         "category": "concept"},
        {"id": "w02q03", "question": "相關係數 r = -0.95 代表什麼？",
         "options": ["幾乎無關", "強正相關", "強負相關", "中等正相關"], "answer": 2,
         "explanation": "r 接近 -1 表示兩個變數有強烈的負向線性關係，即一個上升另一個下降。",
         "category": "concept"},
        {"id": "w02q04", "question": "直方圖 (histogram) 主要用來觀察什麼？",
         "options": ["類別佔比", "變數的分佈形狀", "變數之間的相關性", "時間趨勢"], "answer": 1,
         "explanation": "直方圖將連續變數分成數個區間，顯示每個區間的頻率，用來觀察資料的分佈形狀。",
         "category": "concept"},
        {"id": "w02q05", "question": "以下程式碼做了什麼？\n\ndf.isnull().sum()",
         "options": ["計算每欄的平均值", "計算每欄的缺失值數量",
                     "刪除所有缺失值", "填補缺失值"], "answer": 1,
         "explanation": "isnull() 標記缺失值為 True，.sum() 對每欄加總 True 的數量，得到缺失值計數。",
         "category": "code"},
        {"id": "w02q06", "question": "箱型圖 (box plot) 中的「箱子」代表什麼範圍？",
         "options": ["最小值到最大值", "第一四分位數 (Q1) 到第三四分位數 (Q3)",
                     "平均值 ± 標準差", "中位數 ± 1"], "answer": 1,
         "explanation": "箱型圖的箱子從 Q1 到 Q3，涵蓋中間 50% 的資料，稱為四分位距 (IQR)。",
         "category": "application"},
        {"id": "w02q07", "question": "以下程式碼的作用是？\n\ndf['age'].value_counts()",
         "options": ["計算 age 的平均值", "計算 age 每個值出現的次數",
                     "排序 age 欄位", "刪除 age 的重複值"], "answer": 1,
         "explanation": "value_counts() 統計該欄位每個不同值出現的頻率，並由高到低排列。",
         "category": "code"},
        {"id": "w02q08", "question": "當資料有極端離群值時，應優先使用哪個統計量描述「中心」？",
         "options": ["平均數 (mean)", "中位數 (median)", "眾數 (mode)", "標準差 (std)"], "answer": 1,
         "explanation": "中位數不受極端值影響，比平均數更能代表有離群值資料的中心趨勢。",
         "category": "application"},
        {"id": "w02q09", "question": "熱力圖 (heatmap) 在 EDA 中常用來顯示什麼？",
         "options": ["資料的時間變化", "特徵之間的相關係數矩陣",
                     "模型的損失曲線", "類別的分佈比例"], "answer": 1,
         "explanation": "heatmap 常搭配 df.corr() 使用，以顏色深淺呈現各特徵之間的相關係數。",
         "category": "application"},
        {"id": "w02q10", "question": "以下程式碼的功能是？\n\nimport seaborn as sns\nsns.pairplot(df)",
         "options": ["畫出所有特徵的長條圖", "畫出所有特徵兩兩之間的散佈圖矩陣",
                     "計算所有特徵的相關係數", "刪除高相關的特徵"], "answer": 1,
         "explanation": "pairplot 對 DataFrame 中的所有數值欄位兩兩組合繪製散佈圖，對角線繪製分佈圖。",
         "category": "code"},
    ],

    # ── Week 3  資料分割與交叉驗證 ───────────────────────────────────
    3: [
        {"id": "w03q01", "question": "訓練集和測試集最常見的比例是？",
         "options": ["50/50", "70/30 或 80/20", "95/5", "60/40"], "answer": 1,
         "explanation": "業界最常使用 70/30 或 80/20 的比例，以確保訓練資料充足且有足夠的測試資料評估。",
         "category": "concept"},
        {"id": "w03q02", "question": "交叉驗證的目的是？",
         "options": ["加速訓練", "減少模型偏差", "更可靠地評估模型效能", "增加訓練資料"], "answer": 2,
         "explanation": "交叉驗證讓每筆資料都輪流當驗證集，避免單次分割的偶然性，得到更穩定的效能估計。",
         "category": "concept"},
        {"id": "w03q03", "question": "K-fold 交叉驗證中 K=5，表示資料被分成？",
         "options": ["2 份", "5 份", "10 份", "K 由模型決定"], "answer": 1,
         "explanation": "K-fold 將資料均分為 K 份，每次取 1 份做驗證、其餘做訓練，重複 K 次。",
         "category": "concept"},
        {"id": "w03q04", "question": "以下程式碼的 test_size=0.2 代表什麼？\n\nX_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)",
         "options": ["測試集佔 2%", "測試集佔 20%", "訓練集佔 20%", "隨機種子為 0.2"], "answer": 1,
         "explanation": "test_size=0.2 表示測試集佔全部資料的 20%，其餘 80% 為訓練集。",
         "category": "code"},
        {"id": "w03q05", "question": "為什麼不能用測試集來調整模型？",
         "options": ["測試集太小", "會導致資料洩漏，模型評估不客觀",
                     "測試集沒有標籤", "會使訓練變慢"], "answer": 1,
         "explanation": "若用測試集調整模型，模型會間接學到測試集的資訊，導致評估結果過度樂觀。",
         "category": "concept"},
        {"id": "w03q06", "question": "Stratified K-Fold 與普通 K-Fold 的差異是？",
         "options": ["速度更快", "每一折都保持類別比例一致",
                     "不需要標籤", "只適用於迴歸問題"], "answer": 1,
         "explanation": "Stratified K-Fold 確保每一折中各類別的比例與原始資料相同，適合類別不平衡的情境。",
         "category": "application"},
        {"id": "w03q07", "question": "random_state 參數的作用是？",
         "options": ["隨機選擇演算法", "讓每次分割結果可重現",
                     "增加隨機性", "控制分割數量"], "answer": 1,
         "explanation": "random_state 設定亂數種子，確保每次執行時得到相同的分割結果，方便實驗重現。",
         "category": "application"},
        {"id": "w03q08", "question": "以下程式碼的功能是？\n\nfrom sklearn.model_selection import cross_val_score\nscores = cross_val_score(model, X, y, cv=5)\nprint(scores.mean())",
         "options": ["訓練 5 個不同的模型", "做 5 折交叉驗證並印出平均分數",
                     "將資料分成 5 份並只用第一份", "訓練模型 5 次取最好的"], "answer": 1,
         "explanation": "cross_val_score 執行 K 折交叉驗證回傳每折的分數，scores.mean() 為平均表現。",
         "category": "code"},
        {"id": "w03q09", "question": "Leave-One-Out Cross-Validation (LOOCV) 的 K 等於？",
         "options": ["2", "5", "10", "樣本總數 N"], "answer": 3,
         "explanation": "LOOCV 每次只留 1 個樣本做驗證，其餘全做訓練，因此 K = N（總樣本數）。",
         "category": "concept"},
        {"id": "w03q10", "question": "在時間序列資料上應使用哪種驗證方式？",
         "options": ["隨機 K-Fold", "TimeSeriesSplit（時間序列分割）",
                     "Stratified K-Fold", "Leave-One-Out"], "answer": 1,
         "explanation": "時間序列資料有時間順序，TimeSeriesSplit 確保訓練集都在驗證集之前，避免未來資訊洩漏。",
         "category": "application"},
    ],

    # ── Week 4  梯度下降與線性回歸 ───────────────────────────────────
    4: [
        {"id": "w04q01", "question": "梯度下降中，學習率太大會導致？",
         "options": ["收斂太慢", "發散（損失不收斂）", "過擬合", "完美收斂"], "answer": 1,
         "explanation": "學習率過大會讓參數更新步伐太大，在最優解附近來回跳動甚至發散。",
         "category": "concept"},
        {"id": "w04q02", "question": "MSE 損失函數的全稱是？",
         "options": ["Mean Square Error", "Maximum Standard Error",
                     "Minimum Squared Estimation", "Mean Squared Error"], "answer": 3,
         "explanation": "MSE = Mean Squared Error（均方誤差），計算預測值與實際值差的平方的平均值。",
         "category": "concept"},
        {"id": "w04q03", "question": "線性回歸的假設函數形式是？",
         "options": ["y = wx + b", "y = sigmoid(wx + b)", "y = max(0, wx + b)", "y = e^(wx)"], "answer": 0,
         "explanation": "線性回歸假設輸出是輸入的線性組合 y = wx + b，是最基本的回歸模型。",
         "category": "concept"},
        {"id": "w04q04", "question": "梯度的方向代表什麼？",
         "options": ["損失函數下降最快的方向", "損失函數上升最快的方向",
                     "參數的最佳值", "學習率的方向"], "answer": 1,
         "explanation": "梯度指向函數值增長最快的方向，因此梯度下降法要沿著梯度的「反方向」更新參數。",
         "category": "concept"},
        {"id": "w04q05", "question": "以下程式碼在做什麼？\n\nw = w - lr * dw",
         "options": ["計算損失", "更新權重（梯度下降一步）",
                     "正規化權重", "初始化權重"], "answer": 1,
         "explanation": "這是梯度下降的核心公式：權重沿著梯度的反方向更新，lr 為學習率、dw 為梯度。",
         "category": "code"},
        {"id": "w04q06", "question": "R² (R-squared) 的值為 0.85 代表？",
         "options": ["模型準確率 85%", "模型解釋了 85% 的變異量",
                     "誤差為 85%", "有 85% 的資料被正確分類"], "answer": 1,
         "explanation": "R² 衡量模型所解釋的變異佔總變異的比例，0.85 表示模型解釋了 85% 的資料變異。",
         "category": "application"},
        {"id": "w04q07", "question": "Batch Gradient Descent 與 SGD 的差異是？",
         "options": ["SGD 每次只用一個樣本計算梯度", "Batch GD 速度更快",
                     "SGD 不能收斂", "兩者完全相同"], "answer": 0,
         "explanation": "Batch GD 每次用全部資料計算梯度；SGD 每次只用一個樣本，速度快但更新方向有雜訊。",
         "category": "application"},
        {"id": "w04q08", "question": "以下程式碼的輸出是？\n\nfrom sklearn.linear_model import LinearRegression\nmodel = LinearRegression()\nmodel.fit([[1],[2],[3]], [2,4,6])\nprint(model.coef_)",
         "options": ["[2.]", "[1.]", "[3.]", "[0.]"], "answer": 0,
         "explanation": "資料點 (1,2),(2,4),(3,6) 完美符合 y=2x，因此回歸係數（斜率）為 2。",
         "category": "code"},
        {"id": "w04q09", "question": "多元線性回歸中，若有 5 個特徵，模型需要幾個權重（含截距）？",
         "options": ["5", "6", "10", "25"], "answer": 1,
         "explanation": "每個特徵一個權重再加上一個截距項（bias），所以 5 + 1 = 6 個參數。",
         "category": "application"},
        {"id": "w04q10", "question": "損失函數的等高線圖中，橢圓中心代表什麼？",
         "options": ["學習率", "損失的最小值（最佳參數位置）",
                     "資料的中心", "初始化的權重"], "answer": 1,
         "explanation": "等高線圖的中心是損失函數的最低點，梯度下降的目標就是找到這個最佳參數組合。",
         "category": "concept"},
    ],

    # ── Week 5  邏輯迴歸與決策邊界 ───────────────────────────────────
    5: [
        {"id": "w05q01", "question": "邏輯迴歸的輸出範圍是？",
         "options": ["(-∞, +∞)", "[0, 1]", "[-1, 1]", "[0, ∞)"], "answer": 1,
         "explanation": "邏輯迴歸使用 sigmoid 函數將線性輸出壓縮到 [0, 1] 之間，代表機率值。",
         "category": "concept"},
        {"id": "w05q02", "question": "ROC 曲線的 AUC = 0.5 代表？",
         "options": ["完美分類器", "隨機猜測", "完全錯誤", "過擬合"], "answer": 1,
         "explanation": "AUC=0.5 代表模型的表現與隨機猜測無異，ROC 曲線等同對角線。",
         "category": "concept"},
        {"id": "w05q03", "question": "決策邊界是指？",
         "options": ["損失函數的最低點", "模型區分不同類別的分界線",
                     "訓練集和測試集的分界", "特徵的最大值"], "answer": 1,
         "explanation": "決策邊界是模型在特徵空間中劃分不同類別的界線，邊界上的預測機率為 0.5。",
         "category": "concept"},
        {"id": "w05q04", "question": "Sigmoid 函數的數學式是？",
         "options": ["1 / (1 + e^(-x))", "max(0, x)", "e^x / sum(e^x)", "tanh(x)"], "answer": 0,
         "explanation": "Sigmoid σ(x) = 1/(1+e^(-x))，將任意實數映射到 (0, 1)，常用於二分類。",
         "category": "concept"},
        {"id": "w05q05", "question": "以下程式碼在做什麼？\n\nfrom sklearn.metrics import classification_report\nprint(classification_report(y_true, y_pred))",
         "options": ["訓練分類模型", "輸出 precision、recall、f1-score 等指標",
                     "繪製 ROC 曲線", "計算 MSE"], "answer": 1,
         "explanation": "classification_report 輸出每個類別的 precision、recall、f1-score 和 support。",
         "category": "code"},
        {"id": "w05q06", "question": "在醫療診斷中，漏診（有病說沒病）對應的是？",
         "options": ["False Positive (FP)", "False Negative (FN)",
                     "True Positive (TP)", "True Negative (TN)"], "answer": 1,
         "explanation": "FN 是實際為正但被預測為負的情況，即「有病卻說沒病」，也就是漏診。",
         "category": "application"},
        {"id": "w05q07", "question": "Precision 和 Recall 的調和平均數稱為？",
         "options": ["Accuracy", "F1-Score", "AUC", "Log Loss"], "answer": 1,
         "explanation": "F1-Score = 2 × (Precision × Recall) / (Precision + Recall)，是兩者的調和平均。",
         "category": "application"},
        {"id": "w05q08", "question": "以下程式碼預測的是什麼？\n\nmodel = LogisticRegression()\nmodel.fit(X_train, y_train)\nproba = model.predict_proba(X_test)[:, 1]",
         "options": ["類別標籤", "屬於類別 1 的機率", "損失值", "特徵重要度"], "answer": 1,
         "explanation": "predict_proba 回傳各類別的機率，[:, 1] 取第二欄即「屬於正類(類別1)」的機率。",
         "category": "code"},
        {"id": "w05q09", "question": "邏輯迴歸使用的損失函數是？",
         "options": ["MSE", "Cross-Entropy (交叉熵)", "Hinge Loss", "MAE"], "answer": 1,
         "explanation": "邏輯迴歸使用 Binary Cross-Entropy 作為損失函數，適合衡量機率分佈之間的差異。",
         "category": "application"},
        {"id": "w05q10", "question": "多類別分類時，邏輯迴歸常搭配什麼策略？",
         "options": ["One-vs-Rest (OvR)", "PCA", "Dropout", "Bagging"], "answer": 0,
         "explanation": "OvR 將多類別拆成多個二分類問題，每個分類器判斷「是不是某一類」。",
         "category": "concept"},
    ],

    # ── Week 6  SVM 支撐向量機 ───────────────────────────────────────
    6: [
        {"id": "w06q01", "question": "SVM 的目標是？",
         "options": ["最小化訓練誤差", "最大化分類間隔 (margin)",
                     "最小化特徵數", "最大化訓練樣本數"], "answer": 1,
         "explanation": "SVM 尋找能最大化兩類之間間隔的超平面，讓分類邊界有最大的容錯空間。",
         "category": "concept"},
        {"id": "w06q02", "question": "RBF 核函數可以處理什麼類型的資料？",
         "options": ["只能線性可分", "非線性可分", "只能二分類", "只能數值型"], "answer": 1,
         "explanation": "RBF 核函數將資料映射到高維空間，使原本線性不可分的資料變得可以分開。",
         "category": "concept"},
        {"id": "w06q03", "question": "SVM 中的支撐向量是指？",
         "options": ["所有訓練資料", "距離決策邊界最近的資料點",
                     "誤分類的資料", "離群值"], "answer": 1,
         "explanation": "支撐向量是距離超平面最近的資料點，它們決定了超平面的位置和方向。",
         "category": "concept"},
        {"id": "w06q04", "question": "SVM 的超參數 C 值越大代表？",
         "options": ["允許更多的誤分類（更寬鬆）", "對誤分類懲罰更重（更嚴格）",
                     "核函數更複雜", "間隔更大"], "answer": 1,
         "explanation": "C 是正規化參數，C 越大對分錯的懲罰越重，模型會盡量分對所有訓練資料（可能過擬合）。",
         "category": "concept"},
        {"id": "w06q05", "question": "以下程式碼使用了什麼核函數？\n\nfrom sklearn.svm import SVC\nmodel = SVC(kernel='poly', degree=3)",
         "options": ["線性核", "RBF 核", "三次多項式核", "Sigmoid 核"], "answer": 2,
         "explanation": "kernel='poly' 搭配 degree=3 表示使用三次多項式核函數。",
         "category": "code"},
        {"id": "w06q06", "question": "SVM 中的 gamma 參數影響什麼？",
         "options": ["學習率", "RBF 核函數的影響範圍",
                     "訓練集大小", "類別權重"], "answer": 1,
         "explanation": "gamma 決定單個訓練樣本的影響範圍，gamma 越大影響範圍越小，決策邊界越複雜。",
         "category": "application"},
        {"id": "w06q07", "question": "線性 SVM 和邏輯迴歸的主要區別是？",
         "options": ["SVM 不能做分類", "SVM 最大化間隔而邏輯迴歸最大化似然",
                     "邏輯迴歸速度更慢", "兩者完全相同"], "answer": 1,
         "explanation": "SVM 以最大化間隔為目標，邏輯迴歸以最大化資料的似然（機率）為目標，哲學不同。",
         "category": "application"},
        {"id": "w06q08", "question": "以下程式碼的作用是？\n\nfrom sklearn.preprocessing import StandardScaler\nfrom sklearn.pipeline import make_pipeline\nclf = make_pipeline(StandardScaler(), SVC())",
         "options": ["先標準化再用 SVM 訓練", "先 SVM 再標準化",
                     "只做標準化", "建立隨機森林"], "answer": 0,
         "explanation": "make_pipeline 依序執行步驟：先 StandardScaler 標準化特徵，再用 SVC 訓練分類器。",
         "category": "code"},
        {"id": "w06q09", "question": "為什麼 SVM 在使用前通常需要做特徵縮放？",
         "options": ["減少訓練時間", "SVM 基於距離計算，特徵尺度差異大會影響結果",
                     "增加特徵數量", "讓核函數失效"], "answer": 1,
         "explanation": "SVM 的間隔和核函數計算都依賴距離，若特徵尺度差異大，某些特徵會主導距離計算。",
         "category": "application"},
        {"id": "w06q10", "question": "以下哪種情況最適合使用 SVM？",
         "options": ["資料量極大（百萬筆以上）", "中小型資料集且特徵維度高",
                     "需要機率輸出的場景", "純文字分類不需核函數"], "answer": 1,
         "explanation": "SVM 在中小型、高維度資料上表現優異，但訓練時間隨資料量增長較快，不適合超大資料集。",
         "category": "code"},
    ],

    # ── Week 7  決策樹與集成學習 ─────────────────────────────────────
    7: [
        {"id": "w07q01", "question": "決策樹的分裂準則 Gini Impurity 的最小值是？",
         "options": ["0（純節點）", "0.5", "1", "-1"], "answer": 0,
         "explanation": "Gini Impurity = 0 表示節點中所有樣本都屬於同一類別（純節點），無需再分裂。",
         "category": "concept"},
        {"id": "w07q02", "question": "隨機森林屬於哪種集成方法？",
         "options": ["Boosting", "Bagging", "Stacking", "Blending"], "answer": 1,
         "explanation": "隨機森林使用 Bagging（Bootstrap Aggregating），對資料和特徵進行隨機抽樣建立多棵樹。",
         "category": "concept"},
        {"id": "w07q03", "question": "GBDT 中的 GB 代表？",
         "options": ["Global Best", "Gradient Boosting", "Greedy Base", "General Balanced"], "answer": 1,
         "explanation": "GBDT = Gradient Boosting Decision Tree，使用梯度提升法逐步修正殘差來建立樹。",
         "category": "concept"},
        {"id": "w07q04", "question": "決策樹容易過擬合的原因是？",
         "options": ["模型太簡單", "樹可以長得很深，完美記住訓練資料",
                     "不能處理類別特徵", "訓練速度太慢"], "answer": 1,
         "explanation": "不限深度的決策樹可以對每個訓練樣本建立專屬路徑，完美擬合訓練資料但泛化能力差。",
         "category": "concept"},
        {"id": "w07q05", "question": "以下程式碼的 max_depth=3 代表什麼？\n\nfrom sklearn.tree import DecisionTreeClassifier\nclf = DecisionTreeClassifier(max_depth=3)",
         "options": ["最多建 3 棵樹", "樹的最大深度為 3 層",
                     "每個節點最多 3 個子節點", "最少需要 3 個樣本"], "answer": 1,
         "explanation": "max_depth=3 限制決策樹最多只能有 3 層，是防止過擬合的重要超參數。",
         "category": "code"},
        {"id": "w07q06", "question": "Bagging 和 Boosting 的主要差異是？",
         "options": ["Bagging 平行建樹，Boosting 串行建樹（後一棵修正前一棵的錯誤）",
                     "Bagging 只能用決策樹", "Boosting 速度一定比較快",
                     "兩者完全相同"], "answer": 0,
         "explanation": "Bagging 各棵樹獨立訓練（可平行），Boosting 每棵新樹針對前面的錯誤進行修正（串行）。",
         "category": "application"},
        {"id": "w07q07", "question": "XGBoost 相比傳統 GBDT 的改進包含？",
         "options": ["更多的樹", "正規化、稀疏感知、平行化等工程優化",
                     "不需要調參", "只能用於分類"], "answer": 1,
         "explanation": "XGBoost 加入 L1/L2 正規化、支援稀疏資料、使用近似演算法等優化，效能和速度都更好。",
         "category": "application"},
        {"id": "w07q08", "question": "以下程式碼的功能是？\n\nfrom sklearn.ensemble import RandomForestClassifier\nrf = RandomForestClassifier(n_estimators=100)\nrf.fit(X_train, y_train)\nprint(rf.feature_importances_)",
         "options": ["訓練 100 棵樹並印出特徵重要度", "訓練 100 次並取最好的",
                     "做 100 折交叉驗證", "建立 100 個特徵"], "answer": 0,
         "explanation": "n_estimators=100 建立 100 棵樹，feature_importances_ 顯示每個特徵對分類的貢獻程度。",
         "category": "code"},
        {"id": "w07q09", "question": "Information Gain（資訊增益）使用的度量基礎是？",
         "options": ["Gini Impurity", "Entropy（熵）", "MSE", "Variance"], "answer": 1,
         "explanation": "Information Gain 基於 Entropy（熵），衡量分裂前後資訊不確定性的降低程度。",
         "category": "application"},
        {"id": "w07q10", "question": "以下程式碼繪製的是什麼？\n\nfrom sklearn.tree import plot_tree\nplot_tree(clf, filled=True, feature_names=feature_names)",
         "options": ["學習曲線", "決策樹的視覺化結構",
                     "混淆矩陣", "ROC 曲線"], "answer": 1,
         "explanation": "plot_tree 將決策樹以圖形方式呈現，filled=True 會依類別比例上色，方便理解分裂邏輯。",
         "category": "code"},
    ],

    # ── Week 8  特徵重要度與 SHAP ────────────────────────────────────
    8: [
        {"id": "w08q01", "question": "SHAP 值的理論基礎來自？",
         "options": ["微積分", "博弈論 (Shapley Value)", "資訊理論", "統計假設檢定"], "answer": 1,
         "explanation": "SHAP 基於博弈論中的 Shapley Value，公平地分配每個特徵對預測結果的貢獻。",
         "category": "concept"},
        {"id": "w08q02", "question": "特徵重要度越高表示？",
         "options": ["該特徵值越大", "該特徵對模型預測的影響越大",
                     "該特徵的方差越大", "該特徵缺失值越少"], "answer": 1,
         "explanation": "特徵重要度衡量的是特徵對模型預測的影響程度，而非特徵值本身的大小。",
         "category": "concept"},
        {"id": "w08q03", "question": "SHAP 相較於 Permutation Importance 的優勢是？",
         "options": ["計算更快", "可以解釋個別預測", "只適用於樹模型", "不需要訓練"], "answer": 1,
         "explanation": "SHAP 可以解釋單一樣本的預測結果（局部解釋），而 Permutation Importance 只提供全局重要度。",
         "category": "concept"},
        {"id": "w08q04", "question": "SHAP Summary Plot 中，點的顏色代表什麼？",
         "options": ["預測類別", "特徵值的高低（紅高藍低）",
                     "模型版本", "訓練/測試集"], "answer": 1,
         "explanation": "Summary Plot 中紅色代表特徵值較高，藍色代表特徵值較低，可看出特徵值大小與 SHAP 值的關係。",
         "category": "concept"},
        {"id": "w08q05", "question": "以下程式碼的作用是？\n\nimport shap\nexplainer = shap.TreeExplainer(model)\nshap_values = explainer.shap_values(X_test)",
         "options": ["訓練樹模型", "計算測試集每個樣本每個特徵的 SHAP 值",
                     "做特徵選擇", "繪製決策樹"], "answer": 1,
         "explanation": "TreeExplainer 針對樹模型高效計算 SHAP 值，shap_values 是每個樣本、每個特徵的貢獻量。",
         "category": "code"},
        {"id": "w08q06", "question": "Permutation Importance 的原理是？",
         "options": ["移除特徵後重新訓練", "隨機打亂某特徵的值，觀察效能下降程度",
                     "計算特徵與目標的相關係數", "使用梯度計算重要度"], "answer": 1,
         "explanation": "打亂特徵後若效能大幅下降，代表模型很依賴該特徵，該特徵就很重要。",
         "category": "application"},
        {"id": "w08q07", "question": "SHAP Force Plot 顯示的是什麼？",
         "options": ["模型的整體準確率", "單一預測中每個特徵如何將預測值從基準值推向最終預測",
                     "訓練損失曲線", "特徵之間的相關性"], "answer": 1,
         "explanation": "Force Plot 以箭頭呈現每個特徵對單一預測的正向或負向推力，直觀解釋預測原因。",
         "category": "application"},
        {"id": "w08q08", "question": "以下程式碼的輸出是？\n\nfrom sklearn.inspection import permutation_importance\nresult = permutation_importance(model, X_test, y_test, n_repeats=10)\nprint(result.importances_mean)",
         "options": ["模型準確率", "每個特徵的排列重要度平均值",
                     "特徵的相關係數", "SHAP 值"], "answer": 1,
         "explanation": "permutation_importance 重複打亂特徵 10 次，importances_mean 回傳每個特徵的平均重要度。",
         "category": "code"},
        {"id": "w08q09", "question": "為什麼兩個高度相關的特徵可能都顯示較低的重要度？",
         "options": ["因為它們都不重要", "因為它們互相替代，打亂一個另一個仍能提供資訊",
                     "因為計算有誤", "因為資料量太少"], "answer": 1,
         "explanation": "高相關特徵互為替代品，打亂其中一個時另一個仍保留資訊，導致兩者的重要度都被低估。",
         "category": "application"},
        {"id": "w08q10", "question": "以下哪種圖可以看出特徵重要度的排名？",
         "options": ["SHAP bar plot", "散佈圖", "ROC 曲線", "學習曲線"], "answer": 0,
         "explanation": "SHAP bar plot 以水平長條圖依序呈現每個特徵的平均絕對 SHAP 值，一目了然看出排名。",
         "category": "code"},
    ],

    # ── Week 9  特徵工程與 Pipeline ──────────────────────────────────
    9: [
        {"id": "w09q01", "question": "StandardScaler 的轉換公式是？",
         "options": ["(x - min) / (max - min)", "(x - mean) / std",
                     "x / max", "log(x + 1)"], "answer": 1,
         "explanation": "StandardScaler 將資料轉換為平均值 0、標準差 1 的分佈，公式為 z = (x - mean) / std。",
         "category": "concept"},
        {"id": "w09q02", "question": "One-Hot Encoding 適用於？",
         "options": ["連續型特徵", "類別型特徵", "時序特徵", "影像特徵"], "answer": 1,
         "explanation": "One-Hot Encoding 將類別型特徵轉換為 0/1 的二元向量，避免模型誤解類別順序。",
         "category": "concept"},
        {"id": "w09q03", "question": "Scikit-learn 的 Pipeline 的好處是？",
         "options": ["加速訓練", "避免資料洩漏、程式碼更整潔",
                     "自動選特徵", "不需要調參"], "answer": 1,
         "explanation": "Pipeline 確保前處理步驟在交叉驗證中只在訓練折上 fit，防止測試資料的資訊洩漏到訓練過程。",
         "category": "concept"},
        {"id": "w09q04", "question": "MinMaxScaler 會將資料縮放到什麼範圍？",
         "options": ["[-1, 1]", "[0, 1]", "[0, 100]", "[-0.5, 0.5]"], "answer": 1,
         "explanation": "MinMaxScaler 預設將資料線性縮放到 [0, 1]，公式為 (x - min) / (max - min)。",
         "category": "concept"},
        {"id": "w09q05", "question": "以下程式碼中，ColumnTransformer 的作用是？\n\nfrom sklearn.compose import ColumnTransformer\nct = ColumnTransformer([\n    ('num', StandardScaler(), num_cols),\n    ('cat', OneHotEncoder(), cat_cols)\n])",
         "options": ["對所有欄位做同樣的轉換", "對數值欄和類別欄分別做不同的轉換",
                     "刪除不需要的欄位", "合併兩個資料集"], "answer": 1,
         "explanation": "ColumnTransformer 允許對不同欄位指定不同的轉換方式，例如數值欄標準化、類別欄做 One-Hot。",
         "category": "code"},
        {"id": "w09q06", "question": "為什麼 fit_transform 只能用在訓練集上？",
         "options": ["因為測試集太小", "因為測試集必須用訓練集的統計量來 transform，避免資料洩漏",
                     "因為會報錯", "因為測試集不需要轉換"], "answer": 1,
         "explanation": "Scaler 要用訓練集的 mean/std 來 fit，測試集只能用同樣的統計量 transform，否則會洩漏測試集資訊。",
         "category": "application"},
        {"id": "w09q07", "question": "Label Encoding 適合哪種類別特徵？",
         "options": ["無序類別（如顏色）", "有序類別（如教育程度：國中 < 高中 < 大學）",
                     "連續型特徵", "所有特徵"], "answer": 1,
         "explanation": "Label Encoding 將類別編碼為數字（0, 1, 2…），只有在類別有自然順序時才合理。",
         "category": "application"},
        {"id": "w09q08", "question": "以下程式碼做了什麼？\n\nfrom sklearn.impute import SimpleImputer\nimp = SimpleImputer(strategy='median')\nX_filled = imp.fit_transform(X)",
         "options": ["刪除缺失值", "用中位數填補缺失值",
                     "用平均值填補缺失值", "用 0 填補缺失值"], "answer": 1,
         "explanation": "SimpleImputer(strategy='median') 會用每欄的中位數來填補缺失值。",
         "category": "code"},
        {"id": "w09q09", "question": "特徵工程中，建立「多項式特徵」的目的是？",
         "options": ["減少特徵數量", "捕捉特徵之間的非線性交互效果",
                     "加速訓練", "處理缺失值"], "answer": 1,
         "explanation": "多項式特徵（如 x1×x2、x1²）讓線性模型也能捕捉到特徵之間的非線性關係。",
         "category": "application"},
        {"id": "w09q10", "question": "以下程式碼的 Pipeline 執行順序為何？\n\npipe = Pipeline([\n    ('imputer', SimpleImputer()),\n    ('scaler', StandardScaler()),\n    ('clf', LogisticRegression())\n])\npipe.fit(X_train, y_train)",
         "options": ["StandardScaler → SimpleImputer → LogisticRegression",
                     "SimpleImputer → StandardScaler → LogisticRegression",
                     "LogisticRegression → SimpleImputer → StandardScaler",
                     "三者同時執行"], "answer": 1,
         "explanation": "Pipeline 依列表順序執行：先填補缺失值、再標準化、最後訓練模型。",
         "category": "code"},
    ],

    # ── Week 10  超參數調校與學習曲線 ────────────────────────────────
    10: [
        {"id": "w10q01", "question": "GridSearchCV 的缺點是？",
         "options": ["計算量大（窮舉所有組合）", "無法找到最佳參數",
                     "只能用於線性模型", "不支援交叉驗證"], "answer": 0,
         "explanation": "GridSearchCV 嘗試所有超參數組合，組合數量隨參數數目指數增長，計算量可能非常大。",
         "category": "concept"},
        {"id": "w10q02", "question": "學習曲線可以幫助診斷？",
         "options": ["計算速度", "過擬合或欠擬合", "資料品質", "特徵重要度"], "answer": 1,
         "explanation": "學習曲線比較訓練誤差和驗證誤差隨資料量的變化，藉此判斷模型是過擬合還是欠擬合。",
         "category": "concept"},
        {"id": "w10q03", "question": "Train error 很低但 Val error 很高代表？",
         "options": ["欠擬合", "過擬合", "完美擬合", "資料太少"], "answer": 1,
         "explanation": "訓練誤差低但驗證誤差高，表示模型在訓練集上表現好卻無法泛化，即過擬合。",
         "category": "concept"},
        {"id": "w10q04", "question": "RandomizedSearchCV 和 GridSearchCV 的差異是？",
         "options": ["RandomizedSearchCV 從參數空間隨機取樣，效率更高",
                     "GridSearchCV 速度更快", "RandomizedSearchCV 一定找到最佳解",
                     "兩者用法完全相同"], "answer": 0,
         "explanation": "RandomizedSearchCV 只隨機嘗試固定次數的參數組合，在參數空間大時比窮舉更有效率。",
         "category": "concept"},
        {"id": "w10q05", "question": "以下程式碼的功能是？\n\nfrom sklearn.model_selection import GridSearchCV\nparam_grid = {'C': [0.1, 1, 10], 'kernel': ['rbf', 'linear']}\ngs = GridSearchCV(SVC(), param_grid, cv=5)\ngs.fit(X, y)\nprint(gs.best_params_)",
         "options": ["訓練 SVC 模型", "窮舉 6 種參數組合做 5 折 CV 並輸出最佳參數",
                     "只用 C=1 訓練", "做特徵選擇"], "answer": 1,
         "explanation": "3 個 C × 2 個 kernel = 6 種組合，各做 5 折交叉驗證，best_params_ 回傳最佳組合。",
         "category": "code"},
        {"id": "w10q06", "question": "欠擬合 (underfitting) 的解決方法是？",
         "options": ["減少特徵", "增加模型複雜度或增加特徵",
                     "增加正規化強度", "減少訓練資料"], "answer": 1,
         "explanation": "欠擬合是模型太簡單，可以透過增加模型複雜度、增加特徵或減少正規化來改善。",
         "category": "application"},
        {"id": "w10q07", "question": "Validation Curve 觀察的是什麼？",
         "options": ["不同資料量下的表現", "某個超參數值變化對訓練/驗證分數的影響",
                     "不同模型的比較", "特徵的分佈"], "answer": 1,
         "explanation": "Validation Curve 固定其他條件，改變單一超參數，觀察訓練/驗證分數如何變化。",
         "category": "application"},
        {"id": "w10q08", "question": "以下程式碼的 n_iter=20 代表什麼？\n\nfrom sklearn.model_selection import RandomizedSearchCV\nrs = RandomizedSearchCV(model, param_distributions, n_iter=20, cv=5)",
         "options": ["訓練 20 次", "從參數空間隨機取樣 20 組組合進行評估",
                     "20 折交叉驗證", "最多跑 20 個 epoch"], "answer": 1,
         "explanation": "n_iter=20 表示從參數分佈中隨機取 20 種組合，每組做 5 折 CV 來評估。",
         "category": "code"},
        {"id": "w10q09", "question": "過擬合的解決方法不包含以下哪一項？",
         "options": ["增加訓練資料", "加入正規化", "減少模型複雜度", "增加模型參數量"], "answer": 3,
         "explanation": "增加模型參數量會讓模型更複雜，更容易過擬合，不是解決過擬合的方法。",
         "category": "application"},
        {"id": "w10q10", "question": "以下程式碼繪製的是什麼？\n\nfrom sklearn.model_selection import learning_curve\ntrain_sizes, train_scores, val_scores = learning_curve(model, X, y, cv=5)\nplt.plot(train_sizes, train_scores.mean(axis=1), label='Train')\nplt.plot(train_sizes, val_scores.mean(axis=1), label='Val')",
         "options": ["ROC 曲線", "學習曲線（訓練/驗證分數 vs 資料量）",
                     "損失曲線", "Validation Curve"], "answer": 1,
         "explanation": "learning_curve 回傳不同資料量下的訓練和驗證分數，繪製出來就是學習曲線。",
         "category": "code"},
    ],

    # ── Week 11  神經網路基礎 ────────────────────────────────────────
    11: [
        {"id": "w11q01", "question": "ReLU 激活函數的定義是？",
         "options": ["max(0, x)", "1/(1+e^(-x))", "(e^x - e^(-x))/(e^x + e^(-x))", "x"], "answer": 0,
         "explanation": "ReLU(x) = max(0, x)，當 x > 0 時輸出 x，否則輸出 0，是最常用的激活函數。",
         "category": "concept"},
        {"id": "w11q02", "question": "Dropout 的作用是？",
         "options": ["加速訓練", "防止過擬合", "增加模型複雜度", "處理缺失值"], "answer": 1,
         "explanation": "Dropout 在訓練時隨機將部分神經元關閉，迫使網路不過度依賴任何特定神經元，減少過擬合。",
         "category": "concept"},
        {"id": "w11q03", "question": "Batch Normalization 標準化的是？",
         "options": ["輸入資料", "每一層的輸出（mini-batch 內）",
                     "損失函數", "學習率"], "answer": 1,
         "explanation": "BN 在每個 mini-batch 內對該層的輸出做標準化，穩定訓練過程並加速收斂。",
         "category": "concept"},
        {"id": "w11q04", "question": "為什麼神經網路需要非線性激活函數？",
         "options": ["為了加速計算", "沒有非線性，多層網路等同於單層線性變換",
                     "為了減少參數", "為了處理缺失值"], "answer": 1,
         "explanation": "若所有層都是線性的，多層堆疊結果仍是線性函數，無法學習複雜的非線性模式。",
         "category": "concept"},
        {"id": "w11q05", "question": "以下程式碼建立了什麼結構？\n\nimport torch.nn as nn\nmodel = nn.Sequential(\n    nn.Linear(784, 128),\n    nn.ReLU(),\n    nn.Linear(128, 10)\n)",
         "options": ["CNN 模型", "兩層全連接網路（784→128→10）",
                     "RNN 模型", "自編碼器"], "answer": 1,
         "explanation": "兩個 Linear 層構成全連接網路，784 輸入、128 隱藏神經元、10 輸出，中間用 ReLU 激活。",
         "category": "code"},
        {"id": "w11q06", "question": "Dropout(0.5) 表示？",
         "options": ["保留 50% 的神經元", "保留 50%（隨機關閉 50%）的神經元",
                     "學習率設為 0.5", "將 50% 的權重設為零"], "answer": 1,
         "explanation": "Dropout(0.5) 在訓練時每個神經元有 50% 的機率被暫時關閉，測試時全部啟用。",
         "category": "application"},
        {"id": "w11q07", "question": "反向傳播 (Backpropagation) 的核心數學原理是？",
         "options": ["矩陣乘法", "鏈式法則 (Chain Rule)",
                     "貝氏定理", "傅立葉轉換"], "answer": 1,
         "explanation": "反向傳播利用鏈式法則逐層計算損失對每個參數的梯度，是神經網路訓練的基礎。",
         "category": "application"},
        {"id": "w11q08", "question": "以下程式碼的 loss.backward() 做了什麼？\n\nloss = criterion(output, target)\nloss.backward()\noptimizer.step()",
         "options": ["計算損失", "計算所有參數的梯度（反向傳播）",
                     "更新參數", "前向傳播"], "answer": 1,
         "explanation": "loss.backward() 執行反向傳播，計算損失對模型中所有可訓練參數的梯度。",
         "category": "code"},
        {"id": "w11q09", "question": "Softmax 函數常用在神經網路的哪裡？",
         "options": ["隱藏層的激活函數", "多分類問題的輸出層",
                     "損失函數", "優化器"], "answer": 1,
         "explanation": "Softmax 將輸出轉換為加總為 1 的機率分佈，適合多分類問題的最後一層。",
         "category": "application"},
        {"id": "w11q10", "question": "下列哪個不是常見的優化器？",
         "options": ["SGD", "Adam", "RMSprop", "MaxPool"], "answer": 3,
         "explanation": "MaxPool 是池化層操作，不是優化器；SGD、Adam、RMSprop 都是常見的參數更新方法。",
         "category": "code"},
    ],

    # ── Week 12  CNN 卷積神經網路 ────────────────────────────────────
    12: [
        {"id": "w12q01", "question": "CNN 中卷積核的主要功能是？",
         "options": ["降低維度", "提取局部特徵", "增加參數量", "正規化"], "answer": 1,
         "explanation": "卷積核在輸入影像上滑動，透過加權求和提取邊緣、紋理等局部特徵。",
         "category": "concept"},
        {"id": "w12q02", "question": "Max Pooling 的作用是？",
         "options": ["增加特徵圖大小", "降低空間維度、保留重要特徵",
                     "增加通道數", "初始化權重"], "answer": 1,
         "explanation": "Max Pooling 在局部區域取最大值，減少空間尺寸的同時保留最顯著的特徵。",
         "category": "concept"},
        {"id": "w12q03", "question": "Grad-CAM 可以告訴我們什麼？",
         "options": ["模型的準確率", "模型在影像中關注的區域",
                     "最佳超參數", "訓練時間"], "answer": 1,
         "explanation": "Grad-CAM 利用梯度資訊產生熱力圖，標示出模型在做預測時最關注的影像區域。",
         "category": "concept"},
        {"id": "w12q04", "question": "3×3 卷積核在 5×5 的輸入上（無 padding、stride=1）輸出的大小是？",
         "options": ["5×5", "3×3", "4×4", "1×1"], "answer": 1,
         "explanation": "輸出尺寸 = (輸入 - 核大小) / stride + 1 = (5 - 3)/1 + 1 = 3，所以輸出是 3×3。",
         "category": "application"},
        {"id": "w12q05", "question": "以下程式碼的 out_channels=32 代表什麼？\n\nnn.Conv2d(in_channels=3, out_channels=32, kernel_size=3)",
         "options": ["輸入有 32 個通道", "使用 32 個不同的卷積核，產生 32 個特徵圖",
                     "卷積核大小為 32", "步長為 32"], "answer": 1,
         "explanation": "out_channels=32 表示有 32 個卷積核，每個提取不同的特徵，產生 32 張特徵圖。",
         "category": "code"},
        {"id": "w12q06", "question": "Padding='same' 的效果是？",
         "options": ["輸出尺寸與輸入相同", "不做填充",
                     "只在右邊填充", "填充值為 1"], "answer": 0,
         "explanation": "padding='same' 自動在輸入周圍填充零，讓卷積後的輸出尺寸與輸入相同。",
         "category": "application"},
        {"id": "w12q07", "question": "CNN 相比全連接網路的優勢是？",
         "options": ["參數更多", "參數共享與局部連接，大幅減少參數量",
                     "不需要激活函數", "只能處理文字"], "answer": 1,
         "explanation": "卷積核在整張影像上共享權重（參數共享），且每次只看局部區域（局部連接），參數量遠少於全連接。",
         "category": "application"},
        {"id": "w12q08", "question": "以下程式碼的模型結構是？\n\nmodel = nn.Sequential(\n    nn.Conv2d(1, 16, 3, padding=1),\n    nn.ReLU(),\n    nn.MaxPool2d(2),\n    nn.Flatten(),\n    nn.Linear(16 * 14 * 14, 10)\n)",
         "options": ["一層卷積 + 池化 + 全連接的 CNN",
                     "純全連接網路", "RNN 模型", "自編碼器"], "answer": 0,
         "explanation": "先做 3×3 卷積產生 16 個通道，經 ReLU 和 2×2 池化後展平，最後用全連接層分類。",
         "category": "code"},
        {"id": "w12q09", "question": "Transfer Learning（遷移學習）在 CNN 中的常見做法是？",
         "options": ["從零開始訓練", "使用預訓練模型的卷積層，只重新訓練最後幾層",
                     "只使用全連接層", "不使用 GPU"], "answer": 1,
         "explanation": "預訓練模型已學會通用的視覺特徵，凍結前面的層，只微調後面的層可以快速適應新任務。",
         "category": "concept"},
        {"id": "w12q10", "question": "Stride=2 的卷積操作會讓輸出尺寸？",
         "options": ["不變", "大約減半", "加倍", "變為 1×1"], "answer": 1,
         "explanation": "stride=2 表示卷積核每次移動 2 格，輸出尺寸大約是輸入的一半。",
         "category": "code"},
    ],

    # ── Week 13  RNN / LSTM / Transformer ────────────────────────────
    13: [
        {"id": "w13q01", "question": "RNN 的主要問題是？",
         "options": ["計算太快", "梯度消失/爆炸", "無法處理序列", "記憶體不足"], "answer": 1,
         "explanation": "RNN 在長序列中反覆乘以權重矩陣，梯度會指數級衰減（消失）或增長（爆炸）。",
         "category": "concept"},
        {"id": "w13q02", "question": "LSTM 中的 Cell State 的作用是？",
         "options": ["儲存短期記憶", "長期資訊的傳遞通道",
                     "計算損失", "控制學習率"], "answer": 1,
         "explanation": "Cell State 是 LSTM 的核心，透過門控機制讓資訊可以幾乎不變地沿時間步傳遞，解決長期依賴問題。",
         "category": "concept"},
        {"id": "w13q03", "question": "Transformer 的核心機制是？",
         "options": ["卷積", "自注意力 (Self-Attention)",
                     "池化", "梯度下降"], "answer": 1,
         "explanation": "Self-Attention 讓序列中每個位置都能直接關注其他所有位置，捕捉全局依賴關係。",
         "category": "concept"},
        {"id": "w13q04", "question": "LSTM 有哪三個門 (gate)？",
         "options": ["輸入門、遺忘門、輸出門", "開始門、結束門、暫停門",
                     "卷積門、池化門、全連接門", "正門、負門、中性門"], "answer": 0,
         "explanation": "LSTM 的三個門控制資訊流：遺忘門決定丟棄什麼、輸入門決定加入什麼、輸出門決定輸出什麼。",
         "category": "concept"},
        {"id": "w13q05", "question": "以下程式碼建立的 LSTM 有幾層？\n\nnn.LSTM(input_size=100, hidden_size=256, num_layers=2, batch_first=True)",
         "options": ["1 層", "2 層", "100 層", "256 層"], "answer": 1,
         "explanation": "num_layers=2 表示堆疊 2 層 LSTM，第一層的輸出作為第二層的輸入。",
         "category": "code"},
        {"id": "w13q06", "question": "Attention 機制中的 Q、K、V 分別代表？",
         "options": ["Query、Key、Value", "Question、Knowledge、Vocabulary",
                     "Quantization、Kernel、Vector", "Queue、Keep、Validate"], "answer": 0,
         "explanation": "Query 是查詢、Key 是鍵、Value 是值；透過 Q 和 K 的相似度計算注意力權重，再加權 V。",
         "category": "application"},
        {"id": "w13q07", "question": "Transformer 為什麼需要 Positional Encoding？",
         "options": ["加速訓練", "因為 Self-Attention 本身不含位置資訊，需要額外加入",
                     "減少參數", "處理缺失值"], "answer": 1,
         "explanation": "Self-Attention 對所有位置一視同仁，沒有先後順序概念，Positional Encoding 補充位置資訊。",
         "category": "application"},
        {"id": "w13q08", "question": "以下程式碼的 embedding 層做了什麼？\n\nemb = nn.Embedding(num_embeddings=10000, embedding_dim=128)\noutput = emb(input_ids)",
         "options": ["One-Hot 編碼", "將每個詞的索引轉換為 128 維的密集向量",
                     "計算詞頻", "刪除生僻詞"], "answer": 1,
         "explanation": "Embedding 層將離散的詞索引（0~9999）映射到 128 維的連續向量空間，是 NLP 的基礎。",
         "category": "code"},
        {"id": "w13q09", "question": "GRU 相比 LSTM 的特點是？",
         "options": ["更多的門", "結構更簡單（只有兩個門），計算更快",
                     "效能一定更好", "不能處理序列"], "answer": 1,
         "explanation": "GRU 將 LSTM 的三個門簡化為兩個（重置門和更新門），參數更少，訓練更快。",
         "category": "application"},
        {"id": "w13q10", "question": "以下程式碼中 attention_weights 代表什麼？\n\nscores = torch.matmul(Q, K.transpose(-2, -1)) / math.sqrt(d_k)\nattention_weights = torch.softmax(scores, dim=-1)\noutput = torch.matmul(attention_weights, V)",
         "options": ["模型的權重參數", "每個位置對其他位置的注意力分佈（加總為 1）",
                     "損失函數", "梯度值"], "answer": 1,
         "explanation": "Q 和 K 的點積經 softmax 後得到注意力權重，表示每個位置應該「關注」其他位置的程度。",
         "category": "code"},
    ],

    # ── Week 14  訓練技巧 ────────────────────────────────────────────
    14: [
        {"id": "w14q01", "question": "Early Stopping 在什麼時候停止訓練？",
         "options": ["訓練損失為零", "驗證損失不再下降", "到達指定 epoch",
                     "學習率為零"], "answer": 1,
         "explanation": "Early Stopping 監控驗證損失，當連續數個 epoch 不改善時停止訓練，防止過擬合。",
         "category": "concept"},
        {"id": "w14q02", "question": "Learning Rate Scheduler 的目的是？",
         "options": ["固定學習率", "在訓練過程中動態調整學習率",
                     "增加模型參數", "加速資料載入"], "answer": 1,
         "explanation": "Scheduler 在訓練中降低學習率，先大步靠近最優解，再小步精細調整。",
         "category": "concept"},
        {"id": "w14q03", "question": "資料增強 (Data Augmentation) 的目的是？",
         "options": ["收集更多資料", "人工增加訓練多樣性以減少過擬合",
                     "清理雜訊", "減少訓練時間"], "answer": 1,
         "explanation": "Data Augmentation 透過旋轉、翻轉、裁切等方式產生變化的訓練資料，增加多樣性。",
         "category": "concept"},
        {"id": "w14q04", "question": "以下程式碼的 patience=5 代表什麼？\n\nearly_stopping = EarlyStopping(monitor='val_loss', patience=5)",
         "options": ["最多訓練 5 個 epoch", "若驗證損失連續 5 個 epoch 沒有改善就停止",
                     "每 5 個 epoch 存檔一次", "學習率除以 5"], "answer": 1,
         "explanation": "patience=5 表示容忍驗證損失 5 個 epoch 不改善，超過就觸發 Early Stopping。",
         "category": "code"},
        {"id": "w14q05", "question": "Cosine Annealing 學習率排程的特點是？",
         "options": ["學習率固定不變", "學習率以餘弦曲線平滑降低",
                     "學習率線性增加", "學習率隨機變化"], "answer": 1,
         "explanation": "Cosine Annealing 讓學習率沿餘弦曲線從初始值平滑降低到接近零，訓練更穩定。",
         "category": "concept"},
        {"id": "w14q06", "question": "影像資料增強中，水平翻轉適用於哪類任務？",
         "options": ["文字辨識", "一般物件辨識（如貓狗分類）",
                     "手寫數字辨識（翻轉會改變含義）", "時間序列預測"], "answer": 1,
         "explanation": "貓狗等自然影像水平翻轉後仍然是同一類別，但手寫數字（如 6 和 9）翻轉可能改變含義。",
         "category": "application"},
        {"id": "w14q07", "question": "Warm-up 學習率策略的作用是？",
         "options": ["一開始就用很大的學習率", "訓練初期用小學習率，逐步增大到目標值",
                     "完全不使用學習率", "隨機初始化學習率"], "answer": 1,
         "explanation": "Warm-up 在訓練初期用小學習率避免模型權重劇烈變化，穩定後再增大到正常學習率。",
         "category": "application"},
        {"id": "w14q08", "question": "以下程式碼做了什麼資料增強？\n\ntransform = transforms.Compose([\n    transforms.RandomHorizontalFlip(),\n    transforms.RandomRotation(10),\n    transforms.ToTensor()\n])",
         "options": ["只轉為 Tensor", "隨機水平翻轉和隨機旋轉 ±10 度後轉為 Tensor",
                     "裁切影像", "加入雜訊"], "answer": 1,
         "explanation": "Compose 串接多個轉換：隨機水平翻轉、隨機旋轉 ±10 度、最後轉為 Tensor。",
         "category": "code"},
        {"id": "w14q09", "question": "Label Smoothing 的目的是？",
         "options": ["讓標籤變成浮點數以加速計算", "將硬標籤 (0/1) 軟化，防止模型過度自信",
                     "修正錯誤標籤", "增加類別數量"], "answer": 1,
         "explanation": "Label Smoothing 將 [0,1] 標籤改為 [ε, 1-ε]，避免模型過度自信導致泛化能力下降。",
         "category": "application"},
        {"id": "w14q10", "question": "以下程式碼的 ReduceLROnPlateau 會在什麼時候降低學習率？\n\nscheduler = ReduceLROnPlateau(optimizer, mode='min', factor=0.1, patience=3)",
         "options": ["每個 epoch 都降低", "監控的指標連續 3 個 epoch 不改善時，學習率乘以 0.1",
                     "訓練開始時", "隨機時間點"], "answer": 1,
         "explanation": "mode='min' 監控指標不降低時觸發，patience=3 表示容忍 3 個 epoch，factor=0.1 表示新學習率 = 舊的 ×0.1。",
         "category": "code"},
    ],

    # ── Week 15  模型評估與公平性 ────────────────────────────────────
    15: [
        {"id": "w15q01", "question": "模型的 Accuracy = 95% 但表現很差，最可能的原因是？",
         "options": ["學習率太高", "類別不平衡（95%的樣本是同一類）",
                     "特徵太多", "訓練太久"], "answer": 1,
         "explanation": "當 95% 樣本屬於同一類時，模型全猜多數類就能達到 95% 準確率，但實際上毫無辨別力。",
         "category": "concept"},
        {"id": "w15q02", "question": "什麼是模型的公平性 (Fairness)？",
         "options": ["模型準確率高", "對不同群體有相近的預測表現",
                     "模型訓練快", "使用最新演算法"], "answer": 1,
         "explanation": "公平性要求模型對不同性別、種族等群體的預測品質相當，不因敏感屬性產生歧視。",
         "category": "concept"},
        {"id": "w15q03", "question": "Confusion Matrix 可以看出什麼？",
         "options": ["模型的訓練時間", "各類別的 TP/FP/FN/TN 分布",
                     "特徵的重要度", "學習率的變化"], "answer": 1,
         "explanation": "混淆矩陣以表格呈現各類別的預測正確與錯誤數量，是評估分類模型的基礎工具。",
         "category": "concept"},
        {"id": "w15q04", "question": "在類別不平衡的情況下，哪個指標比 Accuracy 更適合？",
         "options": ["R²", "F1-Score 或 AUC",
                     "MSE", "學習率"], "answer": 1,
         "explanation": "F1-Score 同時考慮 Precision 和 Recall，AUC 衡量不同閾值下的表現，都不受類別比例影響。",
         "category": "application"},
        {"id": "w15q05", "question": "以下程式碼的輸出是？\n\nfrom sklearn.metrics import confusion_matrix\ny_true = [0, 0, 1, 1]\ny_pred = [0, 1, 1, 0]\nprint(confusion_matrix(y_true, y_pred))",
         "options": ["[[2, 0], [0, 2]]", "[[1, 1], [1, 1]]",
                     "[[0, 2], [2, 0]]", "[[1, 0], [0, 1]]"], "answer": 1,
         "explanation": "TN=1, FP=1, FN=1, TP=1，兩個正確兩個錯誤，矩陣為 [[1,1],[1,1]]。",
         "category": "code"},
        {"id": "w15q06", "question": "Demographic Parity（人口統計均等）要求什麼？",
         "options": ["所有人的預測都一樣", "不同群體獲得正預測的比率相同",
                     "模型 100% 準確", "訓練資料完全平衡"], "answer": 1,
         "explanation": "Demographic Parity 要求模型對不同群體（如男/女）給出正預測的比率相當。",
         "category": "application"},
        {"id": "w15q07", "question": "Macro-F1 和 Micro-F1 的差異是？",
         "options": ["完全相同", "Macro 對每個類別平等加權，Micro 按樣本數加權",
                     "Macro 更快計算", "Micro 不能用於多分類"], "answer": 1,
         "explanation": "Macro-F1 先算每類的 F1 再平均（每類等權），Micro-F1 匯總所有類別的 TP/FP/FN 再算。",
         "category": "application"},
        {"id": "w15q08", "question": "以下程式碼計算的是什麼？\n\nfrom sklearn.metrics import roc_auc_score\nauc = roc_auc_score(y_true, y_prob)",
         "options": ["準確率", "ROC 曲線下面積（AUC）",
                     "F1-Score", "混淆矩陣"], "answer": 1,
         "explanation": "roc_auc_score 計算 ROC 曲線下的面積，AUC 越接近 1 代表模型區分正負類的能力越好。",
         "category": "code"},
        {"id": "w15q09", "question": "模型偏見 (Bias) 的常見來源是？",
         "options": ["使用太多特徵", "訓練資料本身就包含社會偏見",
                     "學習率太高", "使用 GPU 訓練"], "answer": 1,
         "explanation": "模型從資料中學習，如果訓練資料反映了歷史歧視或採樣偏差，模型也會學到這些偏見。",
         "category": "concept"},
        {"id": "w15q10", "question": "以下哪個做法可以改善類別不平衡的問題？",
         "options": ["刪除所有少數類樣本", "使用 SMOTE 過採樣或調整 class_weight",
                     "增加訓練 epoch 數", "使用更大的模型"], "answer": 1,
         "explanation": "SMOTE 產生少數類的合成樣本，class_weight 讓模型更重視少數類，都能改善不平衡。",
         "category": "code"},
    ],

    # ── Week 16  MLOps 入門 ──────────────────────────────────────────
    16: [
        {"id": "w16q01", "question": "MLOps 的核心理念是？",
         "options": ["只關注模型訓練", "自動化 ML 的完整生命週期",
                     "只使用雲端服務", "不需要監控"], "answer": 1,
         "explanation": "MLOps 結合 ML 和 DevOps，涵蓋資料處理、訓練、部署、監控等全生命週期的自動化管理。",
         "category": "concept"},
        {"id": "w16q02", "question": "模型版本控制的好處是？",
         "options": ["加速訓練", "可以回溯和比較不同版本的模型",
                     "減少記憶體", "自動調參"], "answer": 1,
         "explanation": "版本控制讓團隊能追蹤模型的演進、比較不同版本的效能、並在需要時回退到先前版本。",
         "category": "concept"},
        {"id": "w16q03", "question": "資料漂移 (Data Drift) 是指？",
         "options": ["訓練資料太少", "生產環境的資料分佈與訓練資料不同",
                     "模型參數變化", "API 速度變慢"], "answer": 1,
         "explanation": "Data Drift 指線上環境的輸入資料分佈隨時間改變，導致模型效能下降。",
         "category": "concept"},
        {"id": "w16q04", "question": "CI/CD 在 MLOps 中代表什麼？",
         "options": ["Continuous Integration / Continuous Deployment",
                     "Code Inspection / Code Design",
                     "Cluster Infrastructure / Cloud Database",
                     "Copy Input / Copy Data"], "answer": 0,
         "explanation": "CI/CD 是持續整合/持續部署，自動化測試和部署流程，確保程式碼和模型品質。",
         "category": "concept"},
        {"id": "w16q05", "question": "以下哪個工具常用於實驗追蹤 (Experiment Tracking)？",
         "options": ["Git", "MLflow 或 Weights & Biases",
                     "Docker", "Kubernetes"], "answer": 1,
         "explanation": "MLflow 和 W&B 可以記錄每次實驗的超參數、指標、模型產出，方便比較和重現。",
         "category": "application"},
        {"id": "w16q06", "question": "Docker 在 MLOps 中的角色是？",
         "options": ["訓練模型", "將應用和依賴打包成可移植的容器，確保環境一致",
                     "版本控制程式碼", "視覺化資料"], "answer": 1,
         "explanation": "Docker 容器封裝了執行環境和依賴套件，確保模型在不同環境（開發/測試/生產）中行為一致。",
         "category": "application"},
        {"id": "w16q07", "question": "模型監控應該追蹤哪些指標？",
         "options": ["只追蹤準確率", "預測延遲、輸入分佈、模型效能指標等",
                     "只追蹤 API 回應時間", "只追蹤伺服器 CPU 使用率"], "answer": 1,
         "explanation": "完整的監控應涵蓋模型效能（精確度等）、系統效能（延遲等）和資料品質（分佈變化等）。",
         "category": "application"},
        {"id": "w16q08", "question": "以下 YAML 是什麼工具的設定檔？\n\nname: ml-pipeline\non: [push]\njobs:\n  test:\n    runs-on: ubuntu-latest\n    steps:\n      - uses: actions/checkout@v4\n      - run: pytest tests/",
         "options": ["Docker", "GitHub Actions（CI/CD 流水線）",
                     "MLflow", "Kubernetes"], "answer": 1,
         "explanation": "這是 GitHub Actions 的工作流程設定，在每次 push 時自動執行 pytest 測試。",
         "category": "code"},
        {"id": "w16q09", "question": "Feature Store 的用途是？",
         "options": ["儲存模型權重", "集中管理和共享特徵定義與計算，避免重複工作",
                     "儲存原始資料", "備份程式碼"], "answer": 1,
         "explanation": "Feature Store 統一管理特徵的計算邏輯和儲存，讓不同團隊和專案可以重用同一套特徵。",
         "category": "application"},
        {"id": "w16q10", "question": "A/B Testing 在模型部署中的作用是？",
         "options": ["測試 API 速度", "將流量分配給新舊模型，比較實際效能差異",
                     "調整超參數", "清理資料"], "answer": 1,
         "explanation": "A/B Testing 將部分使用者導向新模型、其餘使用舊模型，用真實流量比較兩者的表現。",
         "category": "code"},
    ],

    # ── Week 17  RAG 與 LLM 應用 ─────────────────────────────────────
    17: [
        {"id": "w17q01", "question": "RAG 的全稱是？",
         "options": ["Random Access Generation", "Retrieval-Augmented Generation",
                     "Recursive Attention Graph", "Reinforced Agent Guidance"], "answer": 1,
         "explanation": "RAG = Retrieval-Augmented Generation，先檢索相關文件再讓 LLM 基於檢索結果生成回答。",
         "category": "concept"},
        {"id": "w17q02", "question": "文字嵌入 (Text Embedding) 的作用是？",
         "options": ["壓縮檔案", "將文字轉為固定長度的向量表示",
                     "翻譯文字", "加密文字"], "answer": 1,
         "explanation": "Text Embedding 將文字映射到高維向量空間，語意相近的文字在空間中距離較近。",
         "category": "concept"},
        {"id": "w17q03", "question": "Prompt Engineering 中的 Few-shot 是指？",
         "options": ["不給範例", "給少量範例讓 LLM 理解任務格式",
                     "多次呼叫 API", "微調模型"], "answer": 1,
         "explanation": "Few-shot 在 prompt 中提供少量輸入-輸出範例，讓 LLM 理解任務格式和期望的回答方式。",
         "category": "concept"},
        {"id": "w17q04", "question": "RAG 相比直接使用 LLM 的優勢是？",
         "options": ["不需要 LLM", "減少幻覺 (hallucination)，回答有引用來源",
                     "速度更快", "不需要資料庫"], "answer": 1,
         "explanation": "RAG 讓 LLM 基於檢索到的真實文件回答，減少編造內容的風險，且答案可以追溯來源。",
         "category": "concept"},
        {"id": "w17q05", "question": "以下程式碼的作用是？\n\nfrom langchain.text_splitter import RecursiveCharacterTextSplitter\nsplitter = RecursiveCharacterTextSplitter(chunk_size=500, chunk_overlap=50)\nchunks = splitter.split_documents(docs)",
         "options": ["翻譯文件", "將文件切割成 500 字元的段落，相鄰段落重疊 50 字元",
                     "刪除文件中的重複內容", "壓縮文件"], "answer": 1,
         "explanation": "文件切割是 RAG 的關鍵步驟，chunk_overlap 確保段落交界處的資訊不會遺失。",
         "category": "code"},
        {"id": "w17q06", "question": "向量資料庫 (Vector Database) 的主要用途是？",
         "options": ["儲存結構化資料", "儲存嵌入向量並支援高效的相似度搜尋",
                     "儲存模型權重", "儲存日誌檔案"], "answer": 1,
         "explanation": "向量資料庫（如 Chroma、Pinecone）專門儲存嵌入向量，支援快速的最近鄰搜尋。",
         "category": "application"},
        {"id": "w17q07", "question": "LLM 的 Temperature 參數的作用是？",
         "options": ["控制模型大小", "控制輸出的隨機性（越高越隨機、越有創意）",
                     "控制訓練速度", "控制記憶體用量"], "answer": 1,
         "explanation": "Temperature 調整 softmax 的「銳利度」，值越高輸出越隨機多樣，值越低輸出越確定。",
         "category": "application"},
        {"id": "w17q08", "question": "以下 prompt 使用了什麼技巧？\n\n\"你是一位醫學專家。根據以下資料回答問題。\n資料：{context}\n問題：{question}\n請用繁體中文回答。\"",
         "options": ["Zero-shot", "結合角色設定、RAG 上下文注入和語言指定",
                     "Fine-tuning", "Chain-of-Thought"], "answer": 1,
         "explanation": "此 prompt 設定了角色（醫學專家）、注入檢索到的上下文、並指定輸出語言，是常見的 RAG prompt 模板。",
         "category": "code"},
        {"id": "w17q09", "question": "Chunking 策略對 RAG 效能的影響是？",
         "options": ["沒有影響", "chunk 太大會包含過多雜訊，太小會失去上下文",
                     "chunk 越大越好", "chunk 越小越好"], "answer": 1,
         "explanation": "chunk 大小需要平衡：太大時檢索到的段落含太多無關資訊，太小時失去上下文語意完整性。",
         "category": "application"},
        {"id": "w17q10", "question": "Cosine Similarity 在 RAG 中用來做什麼？",
         "options": ["計算文件長度", "衡量查詢向量與文件向量之間的語意相似度",
                     "壓縮向量", "訓練嵌入模型"], "answer": 1,
         "explanation": "Cosine Similarity 計算兩個向量夾角的餘弦值，用來找出與查詢語意最接近的文件段落。",
         "category": "code"},
    ],

    # ── Week 18  專題展示與反思 ──────────────────────────────────────
    18: [
        {"id": "w18q01", "question": "好的 ML 專題報告應包含？",
         "options": ["只有程式碼", "問題定義、方法、結果、反思",
                     "只有結果", "只有理論推導"], "answer": 1,
         "explanation": "完整的專題報告應包含問題動機、資料描述、方法選擇、實驗結果和反思改進方向。",
         "category": "concept"},
        {"id": "w18q02", "question": "模型部署後最重要的是？",
         "options": ["刪除原始資料", "持續監控模型效能",
                     "停止更新", "增加參數"], "answer": 1,
         "explanation": "部署後必須持續監控模型效能和資料分佈變化，及時發現效能下降並更新模型。",
         "category": "concept"},
        {"id": "w18q03", "question": "反思 (Reflection) 在學習中的重要性是？",
         "options": ["浪費時間", "幫助理解自己的學習過程和不足",
                     "增加考試分數", "減少作業量"], "answer": 1,
         "explanation": "反思讓學習者覺察自己的理解程度和盲點，是後設認知的重要環節，能促進深度學習。",
         "category": "concept"},
        {"id": "w18q04", "question": "專題展示時，技術聽眾最關心的是什麼？",
         "options": ["投影片的動畫效果", "方法選擇的理由、實驗設計和結果分析",
                     "程式碼的行數", "使用了多少 GPU"], "answer": 1,
         "explanation": "技術聽眾關注的是方法的合理性、實驗是否嚴謹、以及結果的分析和解讀。",
         "category": "application"},
        {"id": "w18q05", "question": "以下哪個是可重現研究 (Reproducibility) 的要素？",
         "options": ["只分享最終結果", "提供程式碼、資料、環境設定和隨機種子",
                     "只使用商業軟體", "不公開方法細節"], "answer": 1,
         "explanation": "可重現性要求他人能用相同的程式碼、資料和環境設定得到相同的結果。",
         "category": "application"},
        {"id": "w18q06", "question": "在 ML 專案中，以下哪個步驟通常花費最多時間？",
         "options": ["模型訓練", "資料清洗與特徵工程",
                     "模型部署", "撰寫報告"], "answer": 1,
         "explanation": "業界常說「80% 的時間花在資料」，資料收集、清洗、特徵工程是最耗時的步驟。",
         "category": "concept"},
        {"id": "w18q07", "question": "以下哪個不屬於 ML 專案的倫理考量？",
         "options": ["模型是否對特定族群有偏見", "資料隱私是否受到保護",
                     "訓練使用了多少電力（碳排放）", "程式碼使用了哪種程式語言"], "answer": 3,
         "explanation": "程式語言的選擇是技術決策而非倫理議題；公平性、隱私、環境影響才是 ML 倫理的核心。",
         "category": "application"},
        {"id": "w18q08", "question": "以下 README 片段包含了哪些有助於重現的資訊？\n\n\"## 環境\npython==3.11\ntorch==2.0\n## 執行\npython train.py --seed 42\"",
         "options": ["只有程式語言", "Python 版本、套件版本、執行指令和隨機種子",
                     "只有執行指令", "完全沒有有用資訊"], "answer": 1,
         "explanation": "指定 Python 版本、套件版本確保環境一致，seed=42 確保隨機性可重現，這些都是重現的關鍵。",
         "category": "code"},
        {"id": "w18q09", "question": "Ablation Study（消融研究）的目的是？",
         "options": ["增加模型複雜度", "逐一移除組件，觀察其對效能的影響以驗證其貢獻",
                     "加速訓練", "減少程式碼量"], "answer": 1,
         "explanation": "Ablation Study 透過逐一移除或替換系統組件，量化每個組件的實際貢獻。",
         "category": "code"},
        {"id": "w18q10", "question": "這學期學到的 ML 流程正確順序是？",
         "options": ["訓練模型 → 收集資料 → 部署",
                     "定義問題 → 收集/清洗資料 → 特徵工程 → 訓練/評估 → 部署/監控",
                     "部署 → 評估 → 訓練",
                     "寫程式 → 交報告 → 完成"], "answer": 1,
         "explanation": "完整的 ML 流程從問題定義開始，經過資料處理、建模、評估，最後部署並持續監控。",
         "category": "concept"},
    ],
}


def get_quiz(week: int) -> list[dict]:
    """Get quiz questions for a week (without answers or explanations)."""
    questions = QUIZ_BANK.get(week, [])
    return [
        {
            "id": q["id"],
            "question": q["question"],
            "options": q["options"],
            "category": q["category"],
        }
        for q in questions
    ]


def grade_quiz(week: int, answers: dict[str, int]) -> dict:
    """Grade quiz answers. Returns score, corrections, and explanations."""
    questions = QUIZ_BANK.get(week, [])
    if not questions:
        return {"score": 0, "total": 0, "results": []}

    results = []
    correct = 0
    for q in questions:
        user_ans = answers.get(q["id"])
        is_correct = user_ans == q["answer"]
        if is_correct:
            correct += 1
        results.append({
            "id": q["id"],
            "correct": is_correct,
            "correct_answer": q["answer"],
            "user_answer": user_ans,
            "explanation": q["explanation"],
        })

    return {
        "score": correct,
        "total": len(questions),
        "percentage": round(correct / len(questions) * 100, 1),
        "results": results,
    }
